# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LCrDBsFqXdTgXdYTIPAFKlA0X68iiwUE
"""

!pip install streamlit -q

!pip install pyngrok

from pyngrok import ngrok

!streamlit run /content/drive/MyDrive/streamlit_app.py & npx localtunnel --port 8501 & curl ipv4.icanhazip.com